version: '3.8'
services:
    mysql:
        image: mysql:latest
        restart: on-failure
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
            - MYSQL_DATABASE=$DATABASE_NAME
        ports:
            - $DATABASE_PORT:$DATABASE_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
volumes:
    db:
